// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJihuDfZzap6TP54Wqh-d8geuqH19sB1s',
    appId: '1:256791839389:web:649ac680e5ad129b658a74',
    messagingSenderId: '256791839389',
    projectId: 'fir-chat-40ad1',
    authDomain: 'fir-chat-40ad1.firebaseapp.com',
    storageBucket: 'fir-chat-40ad1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhGiefb-AYuJDQP_bN2e_IwmvlmPY6CxM',
    appId: '1:256791839389:android:b7c1416ca63acce9658a74',
    messagingSenderId: '256791839389',
    projectId: 'fir-chat-40ad1',
    storageBucket: 'fir-chat-40ad1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe-Z5hjg-YXyRu7b8xsZPdZvaigkYxhjQ',
    appId: '1:256791839389:ios:1bfdbe85e22080c2658a74',
    messagingSenderId: '256791839389',
    projectId: 'fir-chat-40ad1',
    storageBucket: 'fir-chat-40ad1.appspot.com',
    iosClientId: '256791839389-prkb46nsact8722ebb16iut513n7lqiv.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBe-Z5hjg-YXyRu7b8xsZPdZvaigkYxhjQ',
    appId: '1:256791839389:ios:1508d90d66417a98658a74',
    messagingSenderId: '256791839389',
    projectId: 'fir-chat-40ad1',
    storageBucket: 'fir-chat-40ad1.appspot.com',
    iosClientId: '256791839389-9tsgu2fahkm5o2v8vpqhm1vk6h4hj0jh.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
